global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus' # Scrape itself
    static_configs:
      - targets: ['localhost:9090' ]

  - job_name: 'Express Server' # Scrape the web server
    metrics_path: '/metrics'
    static_configs:
      - targets: ['express-server:443'] # Docker container name
        labels:
          application: "Web server"